const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/nikeTshirt.jpg",
      price: "1000 INR",
      countInStock: 10,
      //? 679 x 829 px
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirt",
    },
    {
      name: "Adidas Trendy Hoody",
      slug: "adidas-trendy-hoody",
      category: "Hoodies",
      image: "/images/adidasHoody.jpg",
      price: "1200 INR",
      countInStock: 10,
      brand: "Adidas",
      rating: 4,
      numReviews: 5,
      description: "High Quality Hoodies",
    },
    {
      name: "Nike Sports Shoes",
      slug: "nike-sports-shoes",
      category: "Shoes",
      image: "/images/jordans.jpg",
      price: "2000 INR",
      countInStock: 4,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Sports Shoes",
    },
    {
      name: "Puma Polo Tshirt",
      slug: "puma-polo-tshirt",
      category: "Shirts",
      image: "/images/polo.jpg",
      price: "1200 INR",
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "Classy Polo Shirt",
    },
  ],
};

export default data;
