const data = {
  products: [
    {
      name: "Nike Womens Jersey",
      slug: "nike-Womens-jersey",
      category: "Shirts",
      image: "/images/nikeTshirt.jpg",
      price: "1000 INR",
      countInStock: 10,
      //? 679 x 829 px
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirt",
    },
    {
      name: "Adidas Trendy Hoody",
      slug: "adidas-trendy-hoody",
      category: "Hoodies",
      image: "/images/adidasHoody.jpg",
      price: "1200 INR",
      countInStock: 10,
      brand: "Adidas",
      rating: 4,
      numReviews: 5,
      description: "High Quality Hoodies",
    },
    {
      name: "Nike Sports Shoes",
      slug: "nike-sports-shoes",
      category: "Shoes",
      image: "/images/jordans.jpg",
      price: "2000 INR",
      countInStock: 4,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Sports Shoes",
    },
    {
      name: "Puma Polo Tshirt",
      slug: "puma-polo-tshirt",
      category: "Shirts",
      image: "/images/polo.jpg",
      price: "1200 INR",
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "Classy Polo Shirt",
    },
    {
      name: "Indian Kurta",
      slug: "indian-kurta-wear",
      category: "Shirts",
      image: "/images/kurta.jpg",
      price: "3200 INR",
      countInStock: 10,
      brand: "Manyavar",
      rating: 4.5,
      numReviews: 10,
      description: "Traditional Rich Kurta",
    },
    {
      name: "3 Piece Suit",
      slug: "formal-suit",
      category: "Suits",
      image: "/images/suits.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Arrow",
      rating: 4.5,
      numReviews: 10,
      description: "Perfect For Weddings And Office Meetings",
    },
    {
      name: "Brasil Jersey",
      slug: "sports-jersey",
      category: "Shirts",
      image: "/images/jersey.jpg",
      price: "1200 INR",
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "World Cup Team Brasil Jersey",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
  ],

  topWears: [
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-1",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-2",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-3",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-4",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
  ],
  footWears: [
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-5",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-6",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-7",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
    {
      name: "Nike Jordans",
      slug: "shoes-jordans-8",
      category: "Shoes",
      image: "/images/jordyns.jpg",
      price: "4200 INR",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Classic Shoes Enrich With Richness",
    },
  ],
};

export default data;
